aliases:
    fleeks: cd ~/src/dotfiles
    latest-fleek-version: nix run https://getfleek.dev/latest.tar.gz -- version
    update-fleek: nix run https://getfleek.dev/latest.tar.gz -- update
allow_broken: false
auto_gc: true
bling: none
blocklist: []
byo_git: false
ejected: false
flakedir: src/dotfiles
git:
    autocommit: false
    autopull: false
    autopush: false
    enabled: false
min_version: 0.8.4
name: Fleek Configuration
overlays: {}
packages:
    - bat
    - btop
    - delta
    - eza
    - fzf
    - gnumake
    - just
    - lazygit
    - lf
    - ncdu
    - ncurses
    - python3
    - ripgrep
    - speedtest-cli
    - starship
    - tmux
    - tree
    - wget
    - yt-dlp
    - zoxide
    - zsh
    - zstd
    - neovim
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
shell: zsh
systems:
    - arch: x86_64
      home: ""
      hostname: brooklyn
      os: linux
      user:
        email: me@nadav.name
        name: Nadav Spiegelman
        ssh_private_key_file: ~/.ssh/main
        ssh_public_key_file: ~/.ssh/main.pub
        username: nadavspi
      username: nadavspi
track: nixos-unstable
unfree: true
users: []
