#! /bin/sh

bspc monitor -d main notes chat task misc

bspc config border_width 4
bspc config window_gap 10
bspc config bottom_padding 25
bspc config focused_border_color "#5d178f"
bspc config presel_feedback_color "#d9a479"

bspc config single_monocle          true
bspc config left_monocle_padding    800
bspc config right_monocle_padding   800

bspc config split_ratio           0.52
bspc config focus_follows_pointer true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Emacs state=tiled
bspc rule -a obsidian desktop="^2"
bspc rule -a discord desktop="^3"
bspc rule -a mpv desktop="^4"
bspc rule -a chromium desktop="^3"

if [ -f ~/.config/bspwm/local.bspwmrc ]; then
  sh ~/.config/bspwm/local.bspwmrc
fi

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
redshift -l "41:-74" &
feh --bg-fill /mnt/nfs/docs/Archive/10-19\ Personal\ documents/16\ Collections/16.03\ Wallpapers/Vista\ big.jpg
xsetroot -cursor_name left_ptr
