#!/usr/bin/env sh

. "$(dirname "$0")"/../.nnn-plugin-helper

printf "pattern: "
read -r pattern

if [ -n "$pattern" ]; then
    printf "%s" "+l" > "$NNN_PIPE"
    eval "ag -l0 --hidden -S $pattern" > "$NNN_PIPE"
fi
