---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages
  package:
    name: "{{ universal_packages }}"
    state: present

- name: Install OS-specific packages
  package:
    name: "{{ os_packages }}"
    state: present

- name: Install nvim python3 provider
  pip:
    name: pynvim
    extra_args: --user --upgrade

- name: Link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - "{{ universal_dotfiles }}"
    - "{{ os_dotfiles }}"

- name: Install neovim plugins
  command: >
    nvim +PlugClean\! +PlugInstall\! +UpdateRemotePlugins +qall



