---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages
  package:
    name: "{{ universal_packages }}"
    state: present
  become: "{{ 'no' if ansible_os_family == 'Darwin' else 'yes' }}"

- name: Install OS-specific packages
  package:
    name: "{{ os_packages }}"
    state: present
  become: "{{ 'no' if ansible_os_family == 'Darwin' else 'yes' }}"

- name: Create .config directory
  file:
    path: ~/.config
    state: directory
    mode: '700'

- name: Link dotfiles
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - "{{ universal_dotfiles }}"
    - "{{ os_dotfiles }}"

- include_role:
    name: neovim
