directory: /mnt/nfs/data/media/music
library: /mnt/nfs/appdata/beets/library.db
plugins: fromfilename edit

import:
    copy: yes
    resume: ask
    incremental: yes
    languages: en he
    log: /mnt/nfs/appdata/beets/beets.log

match:
    strong_rec_thresh: 0.12

paths:
    default: $albumartist/$album%aunique{}/$albumartist - $album%aunique{} - $track - $title

