---
- hosts: all
  pre_tasks:
    - name: Clone dotfiles repo
      git:
        repo: 'https://github.com/nadavspi/dotfiles.git'
        dest: ~/.dotfiles

- hosts: desktops
  roles:
    - shell
    - desktop

- hosts: servers
  become: yes
  roles:
    - shell
