---
- hosts: all
  tasks:
    - name: Install packages
      homebrew:
        update_homebrew: true
        name:
          - bat
          - git-delta
          - tree
          - the_silver_searcher
          - fish
          - tmux
        state: present

    - name: Install nvim python3 provider
      pip:
        name: pynvim
        extra_args: --user --upgrade

    - name: Link dotfiles
      vars:
        dotfiles: "{{ playbook_dir | dirname }}"
      file:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        state: link
      with_items:
        - src: "{{ dotfiles }}/gitconfig"
          dest: ~/.gitconfig
        - src: "{{ dotfiles }}/gitignore"
          dest: ~/.gitignore
        - src: "{{ dotfiles }}/tmux"
          dest: ~/.config/tmux
        - src: "{{ dotfiles }}/fish"
          dest: ~/.config/fish
        - src: "{{ dotfiles }}/nvim"
          dest: ~/.config/nvim
        - src: "{{ dotfiles }}/alacritty"
          dest: ~/.config/alacritty
        - src: "{{ dotfiles }}/yabai"
          dest: ~/.config/yabai
        - src: "{{ dotfiles }}/skhd"
          dest: ~/.config/skhd
        - src: "{{ dotfiles }}/kitty"
          dest: ~/.config/kitty

    - name: Install neovim plugins
      command: >
        nvim +PlugClean\! +PlugInstall\! +UpdateRemotePlugins +qall



