---
- name: Configure ufw to open nextcloud ports
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { rule: 'allow', port: 80, proto: 'tcp' }
    - { rule: 'allow', port: 443, proto: 'tcp' }
    - { rule: 'allow', port: 8443, proto: 'tcp' }
