name: "Build nix"
on:
  pull_request:
     paths:
       - '**.nix'
  push:
     paths:
       - '**.nix'
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: cachix/cachix-action@v12
      with:
        name: nadavspi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix flake check

    - name: Build home manager (shanghai)
      run: nix run "nixpkgs#home-manager" -- build --flake .#nadavspi@shanghai

    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
